(() => {
  'use strict';
  const STORAGE_KEY='hussel-state-v2', LEGACY_KEY='hussel-name-sets-v1', $=(s)=>document.querySelector(s);
  const copy={
    nl:{backup:'Back-up',restore:'Overzetten',participants:'Wie doen er mee?',fixedList:'Vaste namenlijst',listHelp:'Selecteer een lijst of werk eenmalig met losse namen.',rename:'Hernoemen',duplicate:'Dupliceren',delete:'Verwijderen',names:'Namen',onePerLine:'één per regel',duplicatesHelp:'Lege regels en dubbele namen worden overgeslagen.',clear:'Wis invoer',divideHow:'Hoe wil je verdelen?',groupCount:'Aantal groepen',groupSize:'Personen per groep',makeGroups:'Maak de groepjes',theGroups:'De groepjes',redraw:'Opnieuw loten',emptyTitle:'Nog even husselen…',emptyText:'Vul de namen in en maak je eerste verdeling.',excelExport:'Excel (.csv)',distributionName:'Naam van deze verdeling',renameDistribution:'Verdeling hernoemen',history:'Geschiedenis',clearHistory:'Wis geschiedenis',historyEmpty:'Nog geen verdelingen gemaakt.',nameList:'Namenlijst',listName:'Naam van de lijst',cancel:'Annuleren',save:'Opslaan',loose:'Losse invoer',newList:'Nieuwe lijst',renameList:'Lijst hernoemen',minNames:'Voeg minimaal twee verschillende namen toe.',minAmount:'Kies een aantal van minimaal 1.',group:'groep',groups:'groepen',person:'persoon',people:'personen',perGroup:'per groep',addNames:'Voeg namen toe voor een verdeling',chooseMin:'Kies minimaal 1',groupLabel:'Groep',saved:'Namenlijst opgeslagen',renamed:'Naam gewijzigd',duplicated:'Lijst gedupliceerd',deleted:'Lijst verwijderd',restoreDone:'Gegevens overgezet',importError:'Dit is geen geldige Hussel-back-up.',historyCleared:'Geschiedenis gewist',giveName:'Geef de lijst een naam.',existingName:'Er bestaat al een lijst met deze naam.',placeholder:'Bijvoorbeeld Klas 2B',dataset:'Dataset',downloaded:'Bestand gedownload',pdfOpened:'PDF geopend in een nieuw tabblad',spin:'Draai',quickPick:'Kies direct',spinWheel:'Draai aan het wiel',chosen:'Gekozen naam',removeFromWheel:'Verwijder van wiel',close:'Sluiten',wheelEntries:'Namen op het wiel',wheelDatasetHelp:'Wijzigingen hier zijn tijdelijk en veranderen je vaste dataset niet.',wheelOptions:'Wielinstellingen',spinDuration:'Draaitijd',sound:'Geluid',autoRemove:'Winnaar automatisch verwijderen',recentPicks:'Recente keuzes',noPicks:'Nog geen namen gekozen.',shortcutDirect:'kies direct',shortcutSpin:'draai het wiel'},
    fr:{backup:'Sauvegarde',restore:'Transférer',participants:'Qui participe ?',fixedList:'Liste de noms',listHelp:'Sélectionnez une liste ou utilisez des noms ponctuels.',rename:'Renommer',duplicate:'Dupliquer',delete:'Supprimer',names:'Noms',onePerLine:'un par ligne',duplicatesHelp:'Les lignes vides et les doublons sont ignorés.',clear:'Effacer',divideHow:'Comment répartir ?',groupCount:'Nombre de groupes',groupSize:'Personnes par groupe',makeGroups:'Créer les groupes',theGroups:'Les groupes',redraw:'Nouveau tirage',emptyTitle:'Prêt à mélanger…',emptyText:'Ajoutez les noms et créez votre première répartition.',excelExport:'Excel (.csv)',distributionName:'Nom de cette répartition',renameDistribution:'Renommer la répartition',history:'Historique',clearHistory:'Effacer l’historique',historyEmpty:'Aucune répartition créée.',nameList:'Liste de noms',listName:'Nom de la liste',cancel:'Annuler',save:'Enregistrer',loose:'Saisie libre',newList:'Nouvelle liste',renameList:'Renommer la liste',minNames:'Ajoutez au moins deux noms différents.',minAmount:'Choisissez un nombre d’au moins 1.',group:'groupe',groups:'groupes',person:'personne',people:'personnes',perGroup:'par groupe',addNames:'Ajoutez des noms pour voir la répartition',chooseMin:'Choisissez au moins 1',groupLabel:'Groupe',saved:'Liste enregistrée',renamed:'Nom modifié',duplicated:'Liste dupliquée',deleted:'Liste supprimée',restoreDone:'Données transférées',importError:'Ce fichier n’est pas une sauvegarde Hussel valide.',historyCleared:'Historique effacé',giveName:'Donnez un nom à la liste.',existingName:'Une liste porte déjà ce nom.',placeholder:'Par exemple Classe 2B',dataset:'Jeu de données',downloaded:'Fichier téléchargé',pdfOpened:'PDF ouvert dans un nouvel onglet',spin:'Tourner',quickPick:'Choisir directement',spinWheel:'Faire tourner la roue',chosen:'Nom choisi',removeFromWheel:'Retirer de la roue',close:'Fermer',wheelEntries:'Noms sur la roue',wheelDatasetHelp:'Les modifications ici sont temporaires et ne changent pas votre liste enregistrée.',wheelOptions:'Réglages de la roue',spinDuration:'Durée',sound:'Son',autoRemove:'Retirer automatiquement le gagnant',recentPicks:'Choix récents',noPicks:'Aucun nom choisi.',shortcutDirect:'choisir directement',shortcutSpin:'faire tourner la roue'}
  };
  Object.assign(copy.nl,{advancedMode:'Geavanceerde modus',highlight:'Accentueer leerling',rules:'Regels',noRules:'Geen regels ingesteld',setRules:'Regels instellen',divideRules:'Verdelingsregels',rulesHelp:'Kies twee leerlingen en bepaal of ze samen of apart moeten blijven.',addRule:'Regel toevoegen',alwaysRules:'Altijd toepassen voor deze vaste namenlijst',together:'Samen',apart:'Apart',undo:'Herstel',present:'Presenteren',wheelCount:'Aantal wielen',moveTo:'Verplaats naar…',presentationHint:'Sleep leerlingen of gebruik de keuzelijst om de verdeling live aan te passen.'});
  Object.assign(copy.fr,{advancedMode:'Mode avancé',highlight:'Mettre l’élève en évidence',rules:'Règles',noRules:'Aucune règle définie',setRules:'Définir les règles',divideRules:'Règles de répartition',rulesHelp:'Choisissez deux élèves et indiquez s’ils doivent rester ensemble ou séparés.',addRule:'Ajouter une règle',alwaysRules:'Toujours appliquer à cette liste enregistrée',together:'Ensemble',apart:'Séparés',undo:'Annuler',present:'Présenter',wheelCount:'Nombre de roues',moveTo:'Déplacer vers…',presentationHint:'Glissez les élèves ou utilisez la liste pour modifier la répartition en direct.'});
  const e={names:$('#names'),count:$('#name-count'),select:$('#set-select'),menu:$('#set-menu'),menuBtn:$('#set-menu-button'),amount:$('#amount'),amountLabel:$('#amount-label'),hint:$('#distribution-hint'),validation:$('#validation-message'),groups:$('#groups'),empty:$('#empty-state'),summary:$('#results-summary'),redraw:$('#redraw-button'),undo:$('#undo-button'),exports:$('#export-actions'),distributionName:$('#distribution-name'),dialog:$('#set-dialog'),dialogTitle:$('#dialog-title'),setName:$('#set-name'),dialogError:$('#dialog-error'),toast:$('#toast'),historyList:$('#history-list'),historyEmpty:$('#history-empty'),rulesDialog:$('#rules-dialog'),rulesList:$('#rule-list'),rulesSummary:$('#rules-summary'),presentation:$('#presentation')};
  const w={tool:$('#flits-tool'),canvas:$('#wheel'),grid:$('#wheel-grid'),names:$('#wheel-names'),set:$('#wheel-set'),count:$('#wheel-count'),wheelCount:$('#wheel-count-select'),advanced:$('#flash-advanced-mode'),advancedOptions:$('#flash-advanced-options'),duration:$('#spin-duration'),sound:$('#wheel-sound'),autoRemove:$('#auto-remove'),winner:$('#winner'),winnerName:$('#winner-name'),history:$('#wheel-history'),historyEmpty:$('#wheel-history-empty')};
  let state=load(),activeSetId='',dialogMode='new',current=null,toastTimer,selectedMove=null,selectedPresentationMove=null,temporaryRules=[],pinned=new Map(),highlighted=new Set(),undoStack=[];
  let wheelRotations=[0],wheelSpinning=false,lastWinner='',lastWinners=[],wheelBag=[],wheelBagSignature='';
  function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));if(v&&Array.isArray(v.sets)&&Array.isArray(v.history))return{sets:v.sets,history:v.history,language:v.language==='fr'?'fr':'nl',wheelHistory:Array.isArray(v.wheelHistory)?v.wheelHistory:[],wheelSettings:v.wheelSettings||{}};const old=JSON.parse(localStorage.getItem(LEGACY_KEY));return{sets:Array.isArray(old)?old:[],history:[],language:'nl',wheelHistory:[],wheelSettings:{}};}catch{return{sets:[],history:[],language:'nl',wheelHistory:[],wheelSettings:{}};}}
  const t=(k)=>copy[state.language][k], save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state)), uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML;}
  function parse(v){const seen=new Set();return v.split(/\r?\n|,/).map(n=>n.trim()).filter(n=>{const k=n.toLocaleLowerCase(state.language);if(!n||seen.has(k))return false;seen.add(k);return true;});}
  const names=()=>parse(e.names.value), mode=()=>document.querySelector('input[name="mode"]:checked').value, amount=()=>parseInt(e.amount.value,10);
  function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){let r;if(globalThis.crypto?.getRandomValues){const b=new Uint32Array(1);crypto.getRandomValues(b);r=b[0]/4294967296;}else r=Math.random();const j=Math.floor(r*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function group(list,m,n){const count=m==='size'?Math.ceil(list.length/n):Math.min(n,list.length),mixed=shuffle(list);return Array.from({length:count},(_,i)=>{const base=Math.floor(list.length/count),rem=list.length%count,start=i*base+Math.min(i,rem),len=base+(i<rem?1:0);return mixed.slice(start,start+len);});}
  function activeRules(){const saved=state.sets.find(s=>s.id===activeSetId)?.rules;return Array.isArray(saved)?saved:temporaryRules;}
  function rulesSatisfied(groups,rules){const where=new Map();groups.forEach((g,i)=>g.forEach(n=>where.set(n,i)));return rules.every(r=>!where.has(r.a)||!where.has(r.b)||(r.type==='together'?where.get(r.a)===where.get(r.b):where.get(r.a)!==where.get(r.b)));}
  function constrainedGroups(list,m,n,rules=activeRules(),pins=pinned){const count=m==='size'?Math.ceil(list.length/n):Math.min(n,list.length);for(let attempt=0;attempt<700;attempt++){const groups=group(list,m,n);if(pins.size){for(const [person,target] of pins){const source=groups.findIndex(g=>g.includes(person));if(source<0||target>=count||source===target)continue;const targetLimit=Math.ceil(list.length/count),swapIndex=groups[target].findIndex(x=>!pins.has(x));const moving=groups[source].splice(groups[source].indexOf(person),1)[0];if(groups[target].length>=targetLimit&&swapIndex>=0)groups[source].push(groups[target].splice(swapIndex,1)[0]);groups[target].push(moving);}}if(rulesSatisfied(groups,rules))return groups;}return null;}
  function updateRulesSummary(){const count=activeRules().length;e.rulesSummary.textContent=count?(state.language==='nl'?`${count} ${count===1?'regel':'regels'} actief`:`${count} ${count===1?'règle active':'règles actives'}`):t('noRules');}
  function dist(count,m,n){if(!count)return t('addNames');const g=m==='size'?Math.ceil(count/n):Math.min(count,n),lo=Math.floor(count/g),hi=Math.ceil(count/g);return `${g} ${g===1?t('group'):t('groups')} · ${lo===hi?lo:`${lo}–${hi}`} ${t('perGroup')}`;}
  function date(iso){return new Intl.DateTimeFormat(state.language==='fr'?'fr-BE':'nl-BE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(iso));}
  function wheelNames(){return parse(w.names.value);}
  function secureIndex(length){if(length<1)return-1;if(globalThis.crypto?.getRandomValues){const b=new Uint32Array(1),limit=Math.floor(4294967296/length)*length;do{crypto.getRandomValues(b);}while(b[0]>=limit);return b[0]%length;}return Math.floor(Math.random()*length);}
  function nextWheelIndex(list){const signature=JSON.stringify(list);if(signature!==wheelBagSignature||!wheelBag.length){wheelBag=list.map((_,i)=>i);for(let i=wheelBag.length-1;i>0;i--){const j=secureIndex(i+1);[wheelBag[i],wheelBag[j]]=[wheelBag[j],wheelBag[i]];}wheelBagSignature=signature;}if(lastWinner&&wheelBag.length>1&&list[wheelBag[0]]?.trim().charAt(0).toLocaleLowerCase(state.language)===lastWinner.trim().charAt(0).toLocaleLowerCase(state.language)){const alternative=wheelBag.findIndex(index=>list[index]?.trim().charAt(0).toLocaleLowerCase(state.language)!==lastWinner.trim().charAt(0).toLocaleLowerCase(state.language));if(alternative>0)[wheelBag[0],wheelBag[alternative]]=[wheelBag[alternative],wheelBag[0]];}return wheelBag.shift();}
  function renderWheelSets(){if(!w.set)return;const selected=state.wheelSettings.setId||'';w.set.innerHTML=`<option value="">${t('loose')}</option>`+state.sets.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');w.set.value=state.sets.some(s=>s.id===selected)?selected:'';if(!w.names.value&&w.set.value){const set=state.sets.find(s=>s.id===w.set.value);w.names.value=set?.names.join('\n')||'';}updateWheel();}
  const wheelTotal=()=>w.advanced.checked?Math.max(1,Math.min(5,Number(w.wheelCount.value)||1)):1;
  function updateWheelGrid(){const count=wheelTotal();w.grid.className=`wheel-grid wheels-${count}`;const first=w.grid.querySelector('.wheel-wrap');w.grid.innerHTML='';w.grid.append(first);for(let i=1;i<count;i++){const wrap=document.createElement('div');wrap.className='wheel-wrap';wrap.innerHTML=`<div class="wheel-pointer" aria-hidden="true"></div><canvas width="620" height="620" aria-label="${state.language==='nl'?`Rad ${i+1}`:`Roue ${i+1}`}"></canvas>`;w.grid.append(wrap);}wheelRotations=Array.from({length:count},(_,i)=>wheelRotations[i]||0);}
  function updateWheel(){if(!w.canvas)return;updateWheelGrid();const list=wheelNames();w.count.textContent=`${list.length} ${state.language==='nl'?(list.length===1?'naam':'namen'):(list.length===1?'nom':'noms')}`;w.grid.querySelectorAll('canvas').forEach((canvas,i)=>drawWheel(canvas,list,wheelRotations[i]||0));}
  function drawWheel(canvas,list,rotation=0){const ctx=canvas.getContext('2d'),size=canvas.width,c=size/2,r=c-18;ctx.clearRect(0,0,size,size);ctx.save();ctx.translate(c,c);ctx.rotate(rotation);if(!list.length){ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fillStyle='#fff0bd';ctx.fill();ctx.fillStyle='#754400';ctx.font='700 24px system-ui';ctx.textAlign='center';ctx.fillText(state.language==='nl'?'Voeg namen toe':'Ajoutez des noms',0,8);ctx.restore();return;}const colors=['#e7a44c','#f4d47f','#df9365','#efc365','#d8b765','#6f958b'],arc=Math.PI*2/list.length;list.forEach((name,i)=>{const start=i*arc,angle=start+arc/2;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,start,start+arc);ctx.closePath();ctx.fillStyle=colors[i%colors.length];ctx.fill();ctx.strokeStyle='rgba(255,253,247,.86)';ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.rotate(angle);ctx.translate(r*.58,0);ctx.fillStyle='#3f382c';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`700 ${Math.max(11,Math.min(22,220/list.length))}px system-ui`;const label=name.length>18?`${name.slice(0,17)}…`:name;ctx.fillText(label,0,0,Math.max(75,r*.65));ctx.restore();});ctx.restore();}
  function audioContext(){try{const Audio=window.AudioContext||window.webkitAudioContext,audio=window.__flashAudio||(window.__flashAudio=new Audio());if(audio.state==='suspended')audio.resume();return audio;}catch{return null;}}
  function tone(frequency=440,duration=.06,volume=.035){if(!w.sound.checked)return;const audio=audioContext();if(!audio)return;if(audio.state==='suspended'){audio.resume().then(()=>tone(frequency,duration,volume)).catch(()=>{});return;}try{const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=frequency;gain.gain.setValueAtTime(volume,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration);}catch{}}
  function spinSound(){if(!w.sound.checked)return;audioContext();}
  async function prepareWheelAudio(){if(!w.sound.checked)return;const audio=audioContext();if(!audio)return;try{if(audio.state==='suspended')await audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();gain.gain.value=.0001;osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.012);}catch{}}
  function wheelClick(progress){if(!w.sound.checked)return;const audio=audioContext();if(!audio||audio.state==='suspended')return;try{const now=audio.currentTime,variation=secureIndex(1001)/1000-.5;let impulse=window.__flashWoodImpulse;if(!impulse||impulse.sampleRate!==audio.sampleRate){impulse=audio.createBuffer(1,Math.floor(audio.sampleRate*.045),audio.sampleRate);const data=impulse.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,8);window.__flashWoodImpulse=impulse;}const strike=audio.createBufferSource(),filter=audio.createBiquadFilter(),soften=audio.createBiquadFilter(),strikeGain=audio.createGain();strike.buffer=impulse;strike.playbackRate.value=1+variation*.06;filter.type='bandpass';filter.frequency.value=980-progress*130+variation*80;filter.Q.value=.58;soften.type='lowpass';soften.frequency.value=2350-progress*250;soften.Q.value=.42;strikeGain.gain.setValueAtTime(.055+progress*.009+variation*.004,now);strikeGain.gain.exponentialRampToValueAtTime(.0001,now+.043);strike.connect(filter);filter.connect(soften);soften.connect(strikeGain);strikeGain.connect(audio.destination);const bounce=audio.createBufferSource(),bounceFilter=audio.createBiquadFilter(),bounceGain=audio.createGain();bounce.buffer=impulse;bounce.playbackRate.value=.78+variation*.04;bounceFilter.type='lowpass';bounceFilter.frequency.value=1450;bounceGain.gain.setValueAtTime(.014+variation*.002,now+.009);bounceGain.gain.exponentialRampToValueAtTime(.0001,now+.039);bounce.connect(bounceFilter);bounceFilter.connect(bounceGain);bounceGain.connect(audio.destination);const body=audio.createOscillator(),bodyGain=audio.createGain();body.type='sine';body.frequency.setValueAtTime(148-progress*18+variation*5,now);body.frequency.exponentialRampToValueAtTime(92,now+.052);bodyGain.gain.setValueAtTime(.012+progress*.003,now);bodyGain.gain.exponentialRampToValueAtTime(.0001,now+.055);body.connect(bodyGain);bodyGain.connect(audio.destination);strike.start(now);bounce.start(now+.009);body.start(now);strike.stop(now+.048);bounce.stop(now+.055);body.stop(now+.06);}catch{}}
  function recordWinners(winners){lastWinners=[...winners];lastWinner=winners.at(-1)||'';const createdAt=new Date().toISOString();state.wheelHistory.unshift(...winners.map(name=>({name,createdAt})));state.wheelHistory=state.wheelHistory.slice(0,30);save();renderWheelHistory();w.winnerName.innerHTML=winners.map(name=>`<span>${esc(name)}</span>`).join('');$('#remove-winner').hidden=w.autoRemove.checked;w.winner.hidden=false;tone(720,.18,.06);setTimeout(()=>tone(920,.22,.05),130);if(w.autoRemove.checked)removeWheelWinners(winners);}
  function removeWheelWinners(winners=[lastWinner]){const remove=new Set(winners),list=wheelNames().filter(n=>!remove.has(n));w.names.value=list.join('\n');updateWheel();}
  function renderWheelHistory(){w.historyEmpty.hidden=state.wheelHistory.length>0;w.history.innerHTML=state.wheelHistory.map(item=>`<li><strong>${esc(item.name)}</strong><small>${date(item.createdAt)}</small></li>`).join('');}
  function pickIndexes(list,count){const pool=list.map((_,i)=>i),chosen=[];while(pool.length&&chosen.length<count){const next=nextWheelIndex(list),at=pool.indexOf(next);if(at>=0){chosen.push(next);pool.splice(at,1);}}while(chosen.length<count&&pool.length)chosen.push(pool.splice(secureIndex(pool.length),1)[0]);return chosen;}
  function quickPick(){if(wheelSpinning)return;const list=wheelNames(),count=Math.min(wheelTotal(),list.length);if(!list.length){toast(state.language==='nl'?'Voeg eerst namen toe':'Ajoutez d’abord des noms');return;}tone(520,.08,.04);recordWinners(pickIndexes(list,count).map(i=>list[i]));}
  function spinWheel(){if(wheelSpinning)return;const list=wheelNames(),count=Math.min(wheelTotal(),list.length);if(!list.length){toast(state.language==='nl'?'Voeg eerst namen toe':'Ajoutez d’abord des noms');return;}wheelSpinning=true;prepareWheelAudio().finally(()=>runWheelSpin(list,count));}
  function runWheelSpin(list,count){w.winner.hidden=true;const canvases=[...w.grid.querySelectorAll('canvas')].slice(0,count),indexes=pickIndexes(list,count),arc=Math.PI*2/list.length,duration=Number(w.duration.value),began=performance.now(),starts=canvases.map((_,i)=>wheelRotations[i]||0),targets=indexes.map((winnerIndex,i)=>starts[i]+(6+secureIndex(4))*Math.PI*2-((winnerIndex+.5)*arc+starts[i]%(Math.PI*2)));spinSound();let tick=-1;const frame=(now)=>{const p=Math.min(1,(now-began)/duration),ease=1-Math.pow(1-p,4);canvases.forEach((canvas,i)=>{wheelRotations[i]=starts[i]+(targets[i]-starts[i])*ease;drawWheel(canvas,list,wheelRotations[i]);});const currentTick=Math.floor(wheelRotations[0]/arc);if(currentTick!==tick){tick=currentTick;wheelClick(p);}if(p<1)requestAnimationFrame(frame);else{wheelSpinning=false;wheelRotations=targets;recordWinners(indexes.map(i=>list[i]));}};requestAnimationFrame(frame);}
  function applyLanguage(){document.documentElement.lang=state.language;document.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=t(n.dataset.i18n));$('#language-button').textContent=state.language==='nl'?'FR':'NL';$('#language-button').ariaLabel=state.language==='nl'?'Passer au français':'Overschakelen naar Nederlands';e.setName.placeholder=t('placeholder');e.names.placeholder=state.language==='nl'?'Noor\nSem\nYara\nMilan':'Léa\nHugo\nInès\nLouis';renderSets();update();updateRulesSummary();renderHistory();renderWheelHistory();if(current){const remembered={...current};renderGroups(remembered.groups,remembered.names,false,remembered.title);current.historyId=remembered.historyId;}}
  function renderSets(){e.select.innerHTML=`<option value="">${t('loose')}</option>`+state.sets.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');e.select.value=activeSetId;e.menuBtn.disabled=!activeSetId;renderWheelSets();}
  function update(){const list=names(),m=mode();e.count.textContent=`${list.length} ${state.language==='nl'?(list.length===1?'naam':'namen'):(list.length===1?'nom':'noms')}`;e.amountLabel.textContent=m==='groups'?(amount()===1?t('group'):t('groups')):`${amount()===1?t('person'):t('people')} ${t('perGroup')}`;e.hint.textContent=amount()>0?dist(list.length,m,amount()):t('chooseMin');e.validation.hidden=true;if(activeSetId){const s=state.sets.find(x=>x.id===activeSetId);if(s){s.names=list;save();}}}
  function validate(){const list=names();if(list.length<2)return t('minNames');if(!Number.isInteger(amount())||amount()<1)return t('minAmount');if(mode()==='groups'&&amount()>list.length)return state.language==='nl'?`Met ${list.length} namen kun je maximaal ${list.length} groepen maken.`:`Avec ${list.length} noms, vous pouvez créer au maximum ${list.length} groupes.`;return'';}
  function renderGroups(groups,list,scroll=true,title=''){current={groups,names:list,title};e.distributionName.value=title;const advanced=$('#advanced-mode').checked;e.groups.innerHTML=groups.map((g,i)=>`<article class="group-card" data-drop-group="${i}"><header><span>${t('groupLabel')} ${i+1}</span><small>${g.length} ${g.length===1?t('person'):t('people')}</small></header><ol data-drop-group="${i}">${g.map((n,j)=>`<li draggable="${!pinned.has(n)}" tabindex="0" class="${pinned.get(n)===i?'is-pinned ':''}${highlighted.has(n)?'is-highlighted':''}" data-person="${esc(n)}" data-source-group="${i}" data-person-index="${j}" title="${state.language==='nl'?'Sleep naar een andere groep':'Glissez vers un autre groupe'}"><span>${esc(n).slice(0,1).toUpperCase()}</span>${esc(n)}<i aria-hidden="true">⋮⋮</i><button type="button" class="highlight-person" data-highlight-person aria-pressed="${highlighted.has(n)}" aria-label="${t('highlight')}" ${advanced?'':'hidden'}>✦</button><button type="button" class="pin-person" data-pin-person aria-pressed="${pinned.get(n)===i}" aria-label="${state.language==='nl'?`${esc(n)} vastzetten`:`Épingler ${esc(n)}`}">📌</button><button type="button" class="remove-person" data-remove-person aria-label="${state.language==='nl'?`${esc(n)} uit deze verdeling verwijderen`:`Retirer ${esc(n)} de cette répartition`}">×</button></li>`).join('')}</ol></article>`).join('');const sizes=groups.map(g=>g.length),rest=Math.max(...sizes)!==Math.min(...sizes);e.summary.textContent=state.language==='nl'?`${list.length} namen verdeeld over ${groups.length} ${groups.length===1?'groep':'groepen'}${rest?'. Restpersonen zijn eerlijk verdeeld: sommige groepen hebben één persoon meer.':'.'}`:`${list.length} noms répartis en ${groups.length} ${groups.length===1?'groupe':'groupes'}${rest?'. Les personnes restantes sont réparties équitablement.':'.'}`;e.summary.hidden=false;e.empty.hidden=true;e.redraw.hidden=false;e.exports.hidden=false;e.undo.hidden=!undoStack.length;if(scroll&&matchMedia('(max-width:760px)').matches)$('.results-panel').scrollIntoView({behavior:'smooth',block:'start'});}
  function draw(keepPins=false){const error=validate();if(error){e.validation.textContent=error;e.validation.hidden=false;e.names.focus();return;}if(!keepPins){pinned.clear();highlighted.clear();undoStack=[];}const list=names(),groups=constrainedGroups(list,mode(),amount());if(!groups){e.validation.textContent=state.language==='nl'?'Deze combinatie van regels en vastgezette leerlingen is niet mogelijk. Pas de regels aan.':'Cette combinaison de règles et d’élèves épinglés est impossible.';e.validation.hidden=false;return;}const dataset=activeSetId?(state.sets.find(s=>s.id===activeSetId)?.name||t('loose')):t('loose'),createdAt=new Date().toISOString(),title=`${dataset} – ${date(createdAt)}`,id=uid();renderGroups(groups,list,true,title);current.historyId=id;state.history.unshift({id,createdAt,dataset,title,groups});state.history=state.history.slice(0,100);save();renderHistory();}
  function renderHistory(){const advanced=$('#advanced-mode').checked;e.historyEmpty.hidden=state.history.length>0;e.historyList.innerHTML=state.history.map(item=>`<details class="history-item"><summary><span><strong>${esc(item.title||item.dataset)}</strong><small>${esc(item.dataset)} · ${date(item.createdAt)}</small></span><span>${item.groups.length} ${item.groups.length===1?t('group'):t('groups')}</span></summary><div>${item.groups.map((g,i)=>`<p><b>${t('groupLabel')} ${i+1}:</b> ${g.map(esc).join(', ')}</p>`).join('')}<div class="history-actions"><button type="button" data-history="rename" data-id="${item.id}">${t('renameDistribution')}</button><button type="button" data-history="pdf" data-id="${item.id}">PDF</button>${advanced?`<button type="button" data-history="csv" data-id="${item.id}">${t('excelExport')}</button>`:''}<button class="danger-text" type="button" data-history="delete" data-id="${item.id}">${t('delete')}</button></div></div></details>`).join('');}
  function toast(msg){clearTimeout(toastTimer);e.toast.textContent=msg;e.toast.hidden=false;toastTimer=setTimeout(()=>e.toast.hidden=true,2400);}
  function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500);toast(t('downloaded'));}
  function filename(v){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-|-$/g,'').toLowerCase()||'groepen';}
  function csv(record){const rows=[[state.language==='nl'?'Naam verdeling':'Nom de la répartition',record.title||record.dataset],[t('dataset'),record.dataset],[state.language==='nl'?'Datum en uur':'Date et heure',date(record.createdAt)],[],...record.groups.flatMap((g,i)=>[[`${t('groupLabel')} ${i+1}`],...g.map(n=>[n]),[]])];return'\ufeff'+rows.map(r=>r.map(c=>`"${String(c??'').replace(/"/g,'""')}"`).join(';')).join('\r\n');}
  function exportCsv(record=currentRecord()){download(new Blob([csv(record)],{type:'text/csv;charset=utf-8'}),`${filename(record.title||record.dataset)}-${record.createdAt.slice(0,10)}.csv`);}
  function pdfText(v){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7e]/g,'?').replace(/([\\()])/g,'\\$1');}
  function pdf(record){
    const width=842,height=595,margin=30,gap=10,count=record.groups.length;
    const cols=Math.min(count,Math.ceil(Math.sqrt(count*1.55))),rows=Math.ceil(count/cols),cardW=(width-margin*2-gap*(cols-1))/cols,areaTop=478,areaBottom=28,cardH=(areaTop-areaBottom-gap*(rows-1))/rows,maxNames=Math.max(...record.groups.map(g=>g.length)),nameSize=Math.max(3,Math.min(11,(cardH-38)/(Math.max(1,maxNames)*1.45))),line=nameSize*1.42;
    const commands=['0.969 0.957 0.933 rg 0 0 842 595 re f','0.043 0.42 0.345 rg 0 530 842 65 re f'];
    const text=(value,x,y,size=11,bold=false,color='0.09 0.20 0.18')=>commands.push(`${color} rg BT /${bold?'F2':'F1'} ${size} Tf ${x} ${y} Td (${pdfText(value)}) Tj ET`);
    const shorten=(value,size,available)=>{const max=Math.max(4,Math.floor(available/(size*.54)));return value.length>max?`${value.slice(0,max-1)}…`:value;};
    text(shorten(record.title||record.dataset,24,775),30,552,24,true,'1 1 1');text(`${record.dataset}  |  ${date(record.createdAt)}  |  ${count} ${count===1?t('group'):t('groups')}`,31,507,9,false,'0.38 0.45 0.42');
    record.groups.forEach((group,index)=>{const row=Math.floor(index/cols),col=index%cols,x=margin+col*(cardW+gap),top=areaTop-row*(cardH+gap),bottom=top-cardH;commands.push(`1 0.992 0.98 rg 0.86 0.87 0.84 RG 0.7 w ${x} ${bottom} ${cardW} ${cardH} re B`,`0.933 0.969 0.953 rg ${x+.4} ${top-29} ${cardW-.8} 28.6 re f`);text(`${t('groupLabel')} ${index+1}`,x+11,top-19,Math.min(11,cardW/12),true,'0.043 0.42 0.345');text(`${group.length}`,x+cardW-20,top-19,8,true,'0.38 0.45 0.42');group.forEach((name,n)=>{const at=top-45-n*line;commands.push(`0.949 0.929 0.894 rg ${x+11} ${at-2} ${Math.max(5,nameSize)} ${Math.max(5,nameSize)} re f`);text(shorten(name,nameSize,cardW-38),x+27,at,nameSize);});});
    const stream=commands.join('\n'),obj=[null],add=s=>(obj.push(s),obj.length-1),font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'),bold=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'),content=add(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`),page=add(''),pages=add(`<< /Type /Pages /Kids [${page} 0 R] /Count 1 >>`);obj[page]=`<< /Type /Page /Parent ${pages} 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 ${font} 0 R /F2 ${bold} 0 R >> >> /Contents ${content} 0 R >>`;const catalog=add(`<< /Type /Catalog /Pages ${pages} 0 R >>`);let out='%PDF-1.4\n',offset=[0];for(let i=1;i<obj.length;i++){offset[i]=out.length;out+=`${i} 0 obj\n${obj[i]}\nendobj\n`;}const xref=out.length;out+=`xref\n0 ${obj.length}\n0000000000 65535 f \n`+offset.slice(1).map(o=>`${String(o).padStart(10,'0')} 00000 n \n`).join('')+`trailer\n<< /Size ${obj.length} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([out],{type:'application/pdf'});
  }
  function exportPdf(record=currentRecord()){const url=URL.createObjectURL(pdf(record)),tab=window.open(url,'_blank');if(!tab){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.click();}setTimeout(()=>URL.revokeObjectURL(url),60000);toast(t('pdfOpened'));}
  function currentRecord(){const saved=state.history.find(x=>x.id===current.historyId);return saved?{...saved,title:e.distributionName.value.trim()||saved.title}:{title:e.distributionName.value.trim()||current.title,dataset:t('loose'),createdAt:new Date().toISOString(),groups:current.groups};}
  function rememberGroups(){if(current){undoStack.push(current.groups.map(g=>[...g]));undoStack=undoStack.slice(-20);e.undo.hidden=false;}}
  function syncGroups(groups){const historyId=current.historyId,title=current.title;renderGroups(groups,groups.flat(),false,title);current.historyId=historyId;const record=state.history.find(x=>x.id===historyId);if(record){record.groups=groups;save();renderHistory();}}
  function movePerson(source,index,target){if(!current||source===target)return;const groups=current.groups.map(g=>[...g]),person=groups[source]?.[index];if(!person||!groups[target]||pinned.has(person))return;rememberGroups();groups[source].splice(index,1);groups[target].push(person);syncGroups(groups);toast(state.language==='nl'?`${person} verplaatst`:`${person} déplacé(e)`);}
  function removePerson(source,index){if(!current)return;const groups=current.groups.map(g=>[...g]),person=groups[source]?.[index];if(!person)return;rememberGroups();groups[source].splice(index,1);pinned.delete(person);syncGroups(groups);toast(state.language==='nl'?`${person} alleen uit deze verdeling verwijderd`:`${person} retiré(e) uniquement de cette répartition`);}
  function undoGroups(){const groups=undoStack.pop();if(!groups||!current)return;syncGroups(groups);e.undo.hidden=!undoStack.length;toast(state.language==='nl'?'Laatste wijziging hersteld':'Dernière modification annulée');}
  function ruleRow(rule={a:'',b:'',type:'apart'}){const options=names().map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join(''),row=document.createElement('div');row.className='rule-item';row.innerHTML=`<select data-rule-a aria-label="${t('person')}"><option value="">—</option>${options}</select><select data-rule-type><option value="apart">${t('apart')}</option><option value="together">${t('together')}</option></select><select data-rule-b aria-label="${t('person')}"><option value="">—</option>${options}</select><button type="button" data-remove-rule aria-label="${t('delete')}">×</button>`;row.querySelector('[data-rule-a]').value=rule.a;row.querySelector('[data-rule-b]').value=rule.b;row.querySelector('[data-rule-type]').value=rule.type;return row;}
  function openRules(){e.rulesList.innerHTML='';activeRules().forEach(r=>e.rulesList.append(ruleRow(r)));if(!e.rulesList.children.length)e.rulesList.append(ruleRow());$('#persistent-rule-row').hidden=!activeSetId;$('#rules-persistent').checked=!!activeSetId&&Array.isArray(state.sets.find(s=>s.id===activeSetId)?.rules);$('#rules-error').hidden=true;e.rulesDialog.showModal();}
  function saveRules(event){event.preventDefault();const rules=[...e.rulesList.children].map(row=>({a:row.querySelector('[data-rule-a]').value,b:row.querySelector('[data-rule-b]').value,type:row.querySelector('[data-rule-type]').value})).filter(r=>r.a||r.b);if(rules.some(r=>!r.a||!r.b||r.a===r.b)){const error=$('#rules-error');error.textContent=state.language==='nl'?'Kies voor iedere regel twee verschillende leerlingen.':'Choisissez deux élèves différents pour chaque règle.';error.hidden=false;return;}const set=state.sets.find(s=>s.id===activeSetId);if(set&&$('#rules-persistent').checked){set.rules=rules;temporaryRules=[];save();}else{if(set)delete set.rules;temporaryRules=rules;save();}e.rulesDialog.close();updateRulesSummary();toast(state.language==='nl'?'Regels opgeslagen':'Règles enregistrées');}
  function renderPresentation(){if(!current)return;$('#presentation-title').textContent=e.distributionName.value||current.title;$('#presentation-groups').innerHTML=current.groups.map((g,i)=>`<article class="group-card presentation-card" data-presentation-group="${i}"><header><span>${t('groupLabel')} ${i+1}</span><small>${g.length} ${g.length===1?t('person'):t('people')}</small></header><ol>${g.map((n,j)=>`<li draggable="true" tabindex="0" data-presentation-person data-source-group="${i}" data-person-index="${j}"><span>${esc(n).slice(0,1).toUpperCase()}</span><b>${esc(n)}</b><i aria-hidden="true">⋮⋮</i><button type="button" class="remove-person" data-presentation-remove aria-label="${state.language==='nl'?`${esc(n)} uit deze verdeling verwijderen`:`Retirer ${esc(n)} de cette répartition`}">×</button></li>`).join('')}</ol></article>`).join('');}
  function presentGroups(){if(!current)return;renderPresentation();e.presentation.hidden=false;document.body.classList.add('presenting');e.presentation.requestFullscreen?.().catch(()=>{});}
  function presentationMove(source,index,target){if(!current||source===target||!Number.isInteger(target))return;const name=current.groups[source]?.[index];if(!name)return;const wasPinned=pinned.has(name);if(wasPinned)pinned.delete(name);movePerson(source,index,target);if(wasPinned){pinned.set(name,target);const id=current.historyId;renderGroups(current.groups,current.names,false,current.title);current.historyId=id;}renderPresentation();}
  function closePresentation(){if(document.fullscreenElement)document.exitFullscreen?.();e.presentation.hidden=true;document.body.classList.remove('presenting');}
  function openDialog(type){dialogMode=type;e.dialogError.hidden=true;e.dialogTitle.textContent=type==='new'?t('newList'):t('renameList');e.setName.value=type==='rename'?(state.sets.find(s=>s.id===activeSetId)?.name||''):'';e.dialog.showModal();setTimeout(()=>e.setName.focus(),0);}
  function saveDialog(event){event.preventDefault();const name=e.setName.value.trim();if(!name){e.dialogError.textContent=t('giveName');e.dialogError.hidden=false;return;}if(state.sets.some(s=>s.name.toLocaleLowerCase(state.language)===name.toLocaleLowerCase(state.language)&&(dialogMode==='new'||s.id!==activeSetId))){e.dialogError.textContent=t('existingName');e.dialogError.hidden=false;return;}if(dialogMode==='new'){const set={id:uid(),name,names:names()};state.sets.push(set);activeSetId=set.id;}else state.sets.find(s=>s.id===activeSetId).name=name;save();renderSets();e.dialog.close();toast(dialogMode==='new'?t('saved'):t('renamed'));}
  e.names.addEventListener('input',update);e.amount.addEventListener('input',update);document.querySelectorAll('input[name="mode"]').forEach(r=>r.addEventListener('change',update));$('#minus').onclick=()=>{e.amount.value=Math.max(1,amount()-1);update();};$('#plus').onclick=()=>{e.amount.value=Math.min(99,(amount()||0)+1);update();};$('#draw-button').onclick=()=>draw(false);e.redraw.onclick=()=>draw(true);e.undo.onclick=undoGroups;$('#present-button').onclick=presentGroups;$('#presentation-close').onclick=closePresentation;$('#clear-names').onclick=()=>{e.names.value='';update();e.names.focus();};$('#new-set').onclick=()=>openDialog('new');
  e.select.onchange=()=>{activeSetId=e.select.value;temporaryRules=[];pinned.clear();highlighted.clear();const set=state.sets.find(s=>s.id===activeSetId);if(set)e.names.value=set.names.join('\n');renderSets();update();updateRulesSummary();};e.menuBtn.onclick=()=>{e.menu.hidden=!e.menu.hidden;e.menuBtn.ariaExpanded=String(!e.menu.hidden);};document.addEventListener('click',event=>{if(!event.target.closest('.set-row'))e.menu.hidden=true;});
  e.menu.onclick=event=>{const action=event.target.dataset.action;if(!action)return;e.menu.hidden=true;if(action==='rename')openDialog('rename');if(action==='duplicate'){const source=state.sets.find(s=>s.id===activeSetId);let base=state.language==='nl'?'kopie':'copie',name=`${source.name} – ${base}`,i=2;while(state.sets.some(s=>s.name.toLowerCase()===name.toLowerCase()))name=`${source.name} – ${base} ${i++}`;const clone={...source,id:uid(),name,names:[...source.names]};state.sets.push(clone);activeSetId=clone.id;save();renderSets();toast(t('duplicated'));}if(action==='delete'){const source=state.sets.find(s=>s.id===activeSetId),question=state.language==='nl'?`Weet je zeker dat je “${source.name}” wilt verwijderen?`:`Voulez-vous vraiment supprimer « ${source.name} » ?`;if(source&&confirm(question)){state.sets=state.sets.filter(s=>s.id!==activeSetId);activeSetId='';save();renderSets();toast(t('deleted'));}}};
  $('#set-form').onsubmit=saveDialog;$('#dialog-close').onclick=$('#dialog-cancel').onclick=()=>e.dialog.close();$('#rules-button').onclick=openRules;$('#add-rule').onclick=()=>e.rulesList.append(ruleRow());e.rulesList.onclick=event=>{if(event.target.matches('[data-remove-rule]'))event.target.closest('.rule-item').remove();};$('#rules-form').onsubmit=saveRules;$('#rules-close').onclick=$('#rules-cancel').onclick=()=>e.rulesDialog.close();$('#language-button').onclick=()=>{state.language=state.language==='nl'?'fr':'nl';save();applyLanguage();};$('#csv-export').onclick=()=>exportCsv();$('#pdf-export').onclick=()=>exportPdf();
  $('#advanced-mode').onchange=event=>{$('#advanced-options').hidden=!event.target.checked;$('#csv-export').hidden=!event.target.checked;renderHistory();if(current){const id=current.historyId;renderGroups(current.groups,current.names,false,current.title);current.historyId=id;}};
  $('#presentation-groups').addEventListener('click',event=>{const remove=event.target.closest('[data-presentation-remove]'),person=event.target.closest('[data-presentation-person]');if(remove&&person){event.stopPropagation();removePerson(Number(person.dataset.sourceGroup),Number(person.dataset.personIndex));selectedPresentationMove=null;renderPresentation();return;}if(person){document.querySelectorAll('[data-presentation-person]').forEach(n=>n.classList.remove('move-selected'));person.classList.add('move-selected');selectedPresentationMove={source:Number(person.dataset.sourceGroup),index:Number(person.dataset.personIndex)};toast(state.language==='nl'?'Tik nu op de gewenste groep':'Touchez maintenant le groupe souhaité');return;}const card=event.target.closest('[data-presentation-group]');if(card&&selectedPresentationMove){presentationMove(selectedPresentationMove.source,selectedPresentationMove.index,Number(card.dataset.presentationGroup));selectedPresentationMove=null;}});$('#presentation-groups').addEventListener('dragstart',event=>{const person=event.target.closest('[data-presentation-person]');if(person)event.dataTransfer.setData('text/plain',JSON.stringify({source:Number(person.dataset.sourceGroup),index:Number(person.dataset.personIndex)}));});$('#presentation-groups').addEventListener('dragover',event=>{if(event.target.closest('[data-presentation-group]'))event.preventDefault();});$('#presentation-groups').addEventListener('drop',event=>{const card=event.target.closest('[data-presentation-group]');if(!card)return;event.preventDefault();try{const data=JSON.parse(event.dataTransfer.getData('text/plain'));presentationMove(data.source,data.index,Number(card.dataset.presentationGroup));selectedPresentationMove=null;}catch{}});
  e.groups.addEventListener('click',event=>{const highlight=event.target.closest('[data-highlight-person]'),pin=event.target.closest('[data-pin-person]'),person=event.target.closest('[data-source-group]');if(!person||(!highlight&&!pin))return;event.preventDefault();event.stopImmediatePropagation();const name=person.dataset.person,group=Number(person.dataset.sourceGroup),historyId=current.historyId;if(highlight){highlighted.has(name)?highlighted.delete(name):highlighted.add(name);}else{pinned.get(name)===group?pinned.delete(name):pinned.set(name,group);}renderGroups(current.groups,current.names,false,current.title);current.historyId=historyId;toast(highlight?(highlighted.has(name)?(state.language==='nl'?`${name} geaccentueerd`:`${name} mis(e) en évidence`):(state.language==='nl'?`Accent bij ${name} verwijderd`:`Mise en évidence retirée`)):(pinned.has(name)?(state.language==='nl'?`${name} blijft in deze groep`:`${name} reste dans ce groupe`):(state.language==='nl'?`${name} is losgemaakt`:`${name} n’est plus épinglé(e)`)));},true);
  e.groups.addEventListener('dragstart',event=>{const item=event.target.closest('[data-source-group]');if(!item||pinned.has(item.dataset.person)){event.preventDefault();return;}event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',JSON.stringify({source:Number(item.dataset.sourceGroup),index:Number(item.dataset.personIndex)}));});e.groups.addEventListener('dragover',event=>{const card=event.target.closest('[data-drop-group]');if(!card)return;event.preventDefault();document.querySelectorAll('.group-card').forEach(c=>c.classList.remove('drag-target'));card.closest('.group-card').classList.add('drag-target');});e.groups.addEventListener('dragleave',event=>{if(!event.relatedTarget?.closest?.('.group-card'))document.querySelectorAll('.group-card').forEach(c=>c.classList.remove('drag-target'));});e.groups.addEventListener('drop',event=>{event.preventDefault();const target=Number(event.target.closest('[data-drop-group]')?.dataset.dropGroup);document.querySelectorAll('.group-card').forEach(c=>c.classList.remove('drag-target'));try{const data=JSON.parse(event.dataTransfer.getData('text/plain'));movePerson(data.source,data.index,target);}catch{}});e.groups.addEventListener('click',event=>{const remove=event.target.closest('[data-remove-person]'),pin=event.target.closest('[data-pin-person]'),person=event.target.closest('[data-source-group]');if(pin&&person){event.stopPropagation();const name=person.dataset.person,group=Number(person.dataset.sourceGroup);if(pinned.get(name)===group)pinned.delete(name);else pinned.set(name,group);renderGroups(current.groups,current.names,false,current.title);toast(pinned.has(name)?(state.language==='nl'?`${name} blijft in deze groep`:`${name} reste dans ce groupe`):(state.language==='nl'?`${name} is losgemaakt`:`${name} n’est plus épinglé(e)`));return;}if(remove&&person){event.stopPropagation();removePerson(Number(person.dataset.sourceGroup),Number(person.dataset.personIndex));selectedMove=null;return;}if(person){if(pinned.has(person.dataset.person))return;document.querySelectorAll('.group-card li').forEach(n=>n.classList.remove('move-selected'));person.classList.add('move-selected');selectedMove={source:Number(person.dataset.sourceGroup),index:Number(person.dataset.personIndex)};toast(state.language==='nl'?'Tik nu op de gewenste groep':'Touchez maintenant le groupe souhaité');return;}const card=event.target.closest('.group-card');if(card&&selectedMove){const target=Number(card.dataset.dropGroup);movePerson(selectedMove.source,selectedMove.index,target);selectedMove=null;}});
  e.historyList.onclick=event=>{const action=event.target.dataset.history,id=event.target.dataset.id;if(!action)return;const record=state.history.find(x=>x.id===id);if(!record)return;if(action==='rename'){const value=prompt(t('distributionName'),record.title||record.dataset);if(value?.trim()){record.title=value.trim();if(current?.historyId===id){current.title=record.title;e.distributionName.value=record.title;}save();renderHistory();toast(t('renamed'));}}else if(action==='delete'){const q=state.language==='nl'?`“${record.title||record.dataset}” verwijderen uit de geschiedenis?`:`Supprimer « ${record.title||record.dataset} » de l’historique ?`;if(confirm(q)){state.history=state.history.filter(x=>x.id!==id);save();renderHistory();toast(t('deleted'));}}else(action==='pdf'?exportPdf:exportCsv)(record);};e.distributionName.onchange=()=>{if(!current)return;current.title=e.distributionName.value.trim()||current.title;e.distributionName.value=current.title;const record=state.history.find(x=>x.id===current.historyId);if(record){record.title=current.title;save();renderHistory();}};$('#clear-history').onclick=()=>{const q=state.language==='nl'?'Weet je zeker dat je de volledige geschiedenis wilt wissen?':'Voulez-vous vraiment effacer tout l’historique ?';if(state.history.length&&confirm(q)){state.history=[];save();renderHistory();toast(t('historyCleared'));}};
  $('#data-export').onclick=()=>download(new Blob([JSON.stringify({app:'Hussel',version:2,exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'}),`hussel-backup-${new Date().toISOString().slice(0,10)}.json`);
  $('#data-import').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.app!=='Hussel'||!Array.isArray(data.sets)||!Array.isArray(data.history))throw Error();state={sets:data.sets,history:data.history,language:data.language==='fr'?'fr':'nl',wheelHistory:Array.isArray(data.wheelHistory)?data.wheelHistory:[],wheelSettings:data.wheelSettings||{}};activeSetId='';save();applyLanguage();toast(t('restoreDone'));}catch{toast(t('importError'));}event.target.value='';};
  function showTool(tool){const flits=tool==='flits';$('#hussel-tool').hidden=flits;w.tool.hidden=!flits;$('#hussel-tab').classList.toggle('active',!flits);$('#flits-tab').classList.toggle('active',flits);$('#hussel-tab').ariaSelected=String(!flits);$('#flits-tab').ariaSelected=String(flits);document.body.classList.toggle('flits-active',flits);if(flits)updateWheel();}
  document.addEventListener('keydown',event=>{if(w.tool.hidden||event.repeat||event.metaKey||event.ctrlKey||event.altKey)return;const target=event.target,tag=target?.tagName;if(target?.isContentEditable||['INPUT','TEXTAREA','SELECT','BUTTON'].includes(tag))return;if(event.key==='Enter'){event.preventDefault();quickPick();}else if(event.code==='Space'){event.preventDefault();spinWheel();}});
  $('#hussel-tab').onclick=()=>showTool('hussel');$('#flits-tab').onclick=()=>showTool('flits');w.names.oninput=updateWheel;w.set.onchange=()=>{state.wheelSettings.setId=w.set.value;const set=state.sets.find(s=>s.id===w.set.value);if(set)w.names.value=set.names.join('\n');else w.names.value='';save();updateWheel();};w.duration.onchange=()=>{state.wheelSettings.duration=w.duration.value;save();};w.wheelCount.onchange=()=>{state.wheelSettings.wheelCount=w.wheelCount.value;save();updateWheel();};w.advanced.onchange=()=>{state.wheelSettings.advanced=w.advanced.checked;w.advancedOptions.hidden=!w.advanced.checked;save();updateWheel();};w.sound.onchange=()=>{state.wheelSettings.sound=w.sound.checked;save();};w.autoRemove.onchange=()=>{state.wheelSettings.autoRemove=w.autoRemove.checked;$('#remove-winner').hidden=w.autoRemove.checked;save();};$('#spin-wheel').onclick=spinWheel;$('#spin-button').onclick=spinWheel;$('#quick-pick').onclick=quickPick;$('#remove-winner').onclick=()=>{removeWheelWinners(lastWinners);w.winner.hidden=true;};$('#close-winner').onclick=()=>w.winner.hidden=true;$('#clear-wheel-history').onclick=()=>{state.wheelHistory=[];save();renderWheelHistory();};
  w.duration.value=state.wheelSettings.duration||'5000';w.wheelCount.value=state.wheelSettings.wheelCount||'1';w.advanced.checked=state.wheelSettings.advanced===true;w.advancedOptions.hidden=!w.advanced.checked;w.sound.checked=state.wheelSettings.sound!==false;w.autoRemove.checked=state.wheelSettings.autoRemove===true;applyLanguage();
})();
